INSERT INTO FCFO (CODCOLIGADA,CODCFO,NOME,NOMEFANTASIA,CGCCFO,INSCRESTADUAL,PAGREC,RUA,BAIRRO,CIDADE,CODETD,CEP,TELEFONE,FAX,EMAIL,CONTATO,ATIVO,
DATAULTALTERACAO,DATACRIACAO,CAMPOLIVRE,CODMUNICIPIO,INSCRMUNICIPAL,PESSOAFISOUJUR,PAIS,IDCFO,USUARIOCRIACAO,TIPOOPCOMBUSTIVEL,IDPAIS) 
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,getdate(),getdate(),?,?,?,?,?,?,?,?,?)