INSERT INTO TCITMORCAMENTO (CODCOLIGADA, CODCOTACAO, CODCOLCFO, CODCFO, IDPRD, IDMOV, NSEQITMMOV,
VALCOTACAO, VALNEGOCIADO, CODUND, STSITEM, CFOVENCEDOR,  
CODCPG, DATAENTREGA, CODCPGNEGOCIADA, CODMOEDA, 
PRAZOENTREGA) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)