INSERT INTO TCORCAMENTO (CODCOLIGADA, CODCOTACAO, CODCOLCFO, CODCFO, VALPRAZOENTREGA, 
DATENTREGA, VALPRAZOVALIDADE, CODCPG, CODCPGNEGOCIADA, DTHULTENVIO, CODMOEDA, DESPESA)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, getdate(), ?, ?)