SELECT
TMOV.IDMOV AS pedido_rm_id, 
TMOVHISTORICO.HISTORICOCURTO AS comentario 
--TMOV.USUARIOCRIACAO AS usuario_id
FROM TMOV 
LEFT JOIN TMOVHISTORICO
ON TMOVHISTORICO.IDMOV = TMOV.IDMOV
WHERE TMOV.CODCOLIGADA = 1 
AND TMOV.CODTMV = '1.1.04' 
AND TMOV.CODFILIAL = 1
AND TMOV.STATUS = 'A'
AND TMOV.IDMOV > (SELECT intIdAutoIncremento FROM GTI..tbCdIntegracaoScodeTotvs
WHERE vchBancoDeDados LIKE 'CorporeRM'
AND vchTabela LIKE 'TMOV'
AND vchCampo LIKE 'IDMOV')
ORDER BY TMOV.IDMOV