SELECT
TPRD.IDPRD AS insumo_rm_id, 
TPRD.NOMEFANTASIA AS descricao, 
TITMMOV.CODUND AS unidade,
TITMMOV.QUANTIDADE AS quantidade, 
TITMMOV.CODTB2FAT AS marca,
TITMMOVHISTORICO.HISTORICOCURTO AS comentario,
TITMMOV.nseqitmmov AS sequencia
FROM TITMMOV 
INNER JOIN TPRD
ON TPRD.IDPRD = TITMMOV.IDPRD
LEFT JOIN TITMMOVHISTORICO
ON TITMMOVHISTORICO.IDMOV = TITMMOV.IDMOV
WHERE TITMMOV.IDMOV = {0}